# Generated by Django 2.0 on 2018-01-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='happiness',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='is_significant',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
