# Generated by Django 2.0.1 on 2018-01-14 09:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180114_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anger', models.FloatField()),
                ('disgusted', models.FloatField()),
                ('fearful', models.FloatField()),
                ('happy', models.FloatField()),
                ('sad', models.FloatField()),
                ('surprised', models.FloatField()),
                ('neutral', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='data',
        ),
        migrations.AddField(
            model_name='event',
            name='significant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 14, 9, 59, 1, 972329)),
        ),
        migrations.AddField(
            model_name='emotion',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Event'),
        ),
    ]
