# Generated by Django 2.0.1 on 2018-01-14 10:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180114_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 14, 10, 0, 12, 864620, tzinfo=utc)),
        ),
    ]
