# Generated by Django 2.0.1 on 2018-01-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180114_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotion',
            name='event',
        ),
    ]
