# Generated by Django 2.0.1 on 2018-01-14 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180114_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='child',
            new_name='camera',
        ),
    ]
